### ISSUE TITLE
Can't open minminguard app after enabling in edxposed! 

### ISSUE THREAD

**Issue by Morakhiyasaiyam** [chiehmin/MinMinGuard#185]
I installed minminguard succesfully! If i open app before activating it in edxposed then it open but after enabling and reboot app icon change to unknown app icon and after taping its icon app is force closing! 

Magisk 19.0
Edxposed 3.1.8
Minminguard 2.0.5
![photo_2019-04-14_07-31-13](https://user-images.githubusercontent.com/19637914/56089757-7fef6e00-5eb5-11e9-92d9-1f77a6407118.jpg)
![photo_2019-04-14_07-31-05](https://user-images.githubusercontent.com/19637914/56089761-8a116c80-5eb5-11e9-9168-8ed0c259608a.jpg)
![photo_2019-04-14_07-30-47](https://user-images.githubusercontent.com/19637914/56089763-91387a80-5eb5-11e9-88b3-6a7deeec6ad5.jpg)

**Comment by killer7Mod** [comment]
this is a bug in MIUI 10 with edxposed. There are several problems in the resource hook

**Comment by Wei-ss** [comment]
Same here.

Samsung S8
Magisk 19.2
Oreo 8.0
EdXposed

**Comment by MSkjel** [comment]
Try the newest version from the Xposed repo. If that doesnt work, dump the logcat and post it here please

**Comment by yipinghuang1991** [comment]
Xiaomi 4c, AICP Oreo, Magisk 19.2, Edxposed 0.4.2.3 (Sandhook) with EdXposed Manager 4.4.8

This still persists with Minminguard 2.0.7.
But it seems that the module is working even though the app crashes on open.

I can't provide the edxposed log file because EdXposed Manager is bugged now.

This problem does not exist when I switch back to the usual Xposed v90-beta3.

By the way, PerfectColorBar 1.5.2 also has this problem on my end.

**Comment by MSkjel** [comment]
Yes, it seems to be a EdXposed related issue. It does not happen on EdXposed 0.2.9.8. I will have to check what EdXposed does differently

**Comment by yipinghuang1991** [comment]
2.0.8 solves the problem on my end.
