### ISSUE TITLE
Twee

### ISSUE THREAD

**Issue by uraid** [chiehmin/MinMinGuard#89]
App: Twee
Link: https://play.google.com/store/apps/details?id=se.ja1984.twee&hl=en

MinMinGuard in the latest updates (2.0 update 10+) removes the functionality of the app.
It detects the ads but remove all of the page (happens almost on all the pages there).
You can't use the app this way.

**Comment by chiehmin** [comment]
Ok, I will try to fix it soon.

**Comment by yairh** [comment]
Wow that was a fast reply! :)

**Comment by ja1984** [comment]
@chiehmin Have you been able to look in to this? I'm the dev of Twee and it's really frustrating having users running in to problems due to the plugin =/ I really don't mind people removing the ads like this but there is a bigger problem here I belive.

(I don't have root on my phone so I can't really test it our myself) but I have tried adding your code for removing the ads and putting it in Twee to see if I can reproduce but I'm not able to.

Also it looks like it's enough to just have MinMinGuard running/activated even if you white list Twee and remove the ads by paying or using a code the app still turns blank.

I would really really appriciate if you could look in to this one more time! :) Please let me know if I can help you out in any way!

Thanks

//Jonathan

**Comment by Gitoffthelawn** [comment]
@ja1984 Jonathan, I just have to take a moment of my time to say that your response is so friendly and thoughtful.  You are a model for all developers.

**Comment by terzaghii** [comment]
I also have the same issues as @yairh. Whitelisting Twee does not fix it. I hope you guys can find a way to solve this issue soon!

**Comment by zzhhbyt1** [comment]
ja1984 is so friendly! And cute~

**Comment by ja1984** [comment]
Thanks for the kind comments people, and especially you @zzhhbyt1 ;)

Let's just hope that @chiehmin har the time to look in to this soonish!

**Comment by jaredrummler** [comment]
Same problem with BusyBox for Android: https://github.com/jrummyapps/BusyBox

I don't really have the time to go look through your code and find out why it's doing this. I don't appreciate the 1 star reviews from users. Hopefully you can fix this soon.
